### ISSUE TITLE
IE 7 Crashes

### ISSUE THREAD

**Issue by troyblank** [Schepp/box-sizing-polyfill#7]
because of the lines (71 and 72):

element.runtimeStyle.width = "";
element.runtimeStyle.height = "";

ie 7 crashes when refreshing the page using internet explorer 7, or when click on a link on the page htc is loaded. Not sure the correct way to fix this, you can reproduce this by refreshing a page that has boxsizing.htc is loaded, then try again by commenting out those two lines and you will notice it will not crash.

**Comment by tarcon** [comment]
Same here.

Internet Explorer 7.0.5730.13 on Win XP Home

**Comment by tarcon** [comment]
Crash occurs if a stylesheet sets height:100% in the html selector:

html {
    height:100%;
}

**Comment by troyblank** [comment]
I can confirm, style sheet has HTML height of 100% and crash seems to happen when this is set. Too bad I can not change that without the site blowing up :( ... looks like alternative ie 7 style sheet is needed for me :)

This crash has occurred in many different version of IE 7 in my experience , so I don't think it's version or environment dependent.

**Comment by Schepp** [comment]
Hey guys,

I cannot reproduce this bug with a testpage where I just set 

```
html {height: 100%;}
```

So there must be more involved.
Does this bug also happen when you exchange lines 71 and 72 with the following code:

```
element.runtimeStyle.removeAttribute("width");
element.runtimeStyle.removeAttribute("height");
```

**Comment by Schepp** [comment]
Sorry, I meant removeAttribute and just updated my post above.

**Comment by tarcon** [comment]
The problem occurs in concurrence with Modernizr. 
Minimal example:

``` html
<!doctype html>
<head>
    <style type="text/css">
        * { 
            *behavior: url(js/fixes/boxsizing.htc); 
        }

        html {
            height: 100%;
        }
    </style>
    <script src="http://modernizr.com/downloads/modernizr-latest.js"></script>
</head>
<body>
</body>
</html>
```

**Comment by tarcon** [comment]
Sorry, replacing the lines does not fix the problem.

**Comment by tarcon** [comment]
Correction: apparently, replacing the lines fixes the problem in the minimal example, but not in my full project.
I'll try to do a few more tests.

**Comment by tarcon** [comment]
The minimal example can be reduced to the following and crashes ie7 on refresh regardless of the html { height:100% } style - given the original code lines 71/72:

``` html
<!doctype html>
<head>
    <style type="text/css">
        * { 
            *behavior: url(js/fixes/boxsizing.htc); 
        }
    </style>
    <script src="http://modernizr.com/downloads/modernizr-latest.js"></script>
</head>
<body>
</body>
</html>
```

Removing the html { height:100% } style in my full project however prevents it from crashing for both code versions.
I'll continue testing and try to prepare another example.

**Comment by Schepp** [comment]
Yay! That one "worked" for me, too. I took some countermeasures and updated the polyfill. Would you be so kind to check if that also solves your problems?

**Comment by tarcon** [comment]
Thank you.

My project still crashes.
I have derived a new example which crashes unless you remove the html{ height:100%} style:

``` html
<!doctype html>
<head>
    <style type="text/css">
        * { 
            box-sizing: border-box; *behavior: url(js/fixes/boxsizing.htc);
        }
        html {
            height: 100%;
        }
    </style>
    <script src="http://modernizr.com/downloads/modernizr-latest.js"></script>
</head>
<body>
</body>
</html>

```

**Comment by Schepp** [comment]
Thanks, Greg!

I committed another update. How is that working together with your site?

**Comment by tarcon** [comment]
Works.
Thanks.

**Comment by Schepp** [comment]
Yeah!

**Comment by troyblank** [comment]
This does not fix my issue, it works in compatibility mode in IE 9, but I have tried ie 7 7.0.6002.18005 on a vista 32 VM and it crashes on every link click or refresh just like it did before. Clients have reported crashes too; sorry I wish I could share the site.

**Comment by troyblank** [comment]
Wait sorry, you must have done more than replaced those two lines of code, as that's all I was doing to try to fix it. I have since re-cloned the repo and used the new htc file and no more crashes; thanks a lot for fixing this you are the best!
